// 76개 진단 데이터 (hub에서 추출)
export interface SiteInfo {
  name: string;
  title: string;
  keywords: string;
  target: string;
  category: string;
  url: string;
  emoji: string;
}

export const SITES: SiteInfo[] = [
  {"name": "adhd-focus-radar", "title": "ADHD 포커스 진단", "keywords": "주의력 결핍, 집중력, 업무 효율", "target": "집중력 문제로 고민하는 직장인·학생", "category": "건강·습관", "url": "https://adhd-focus-radar.pomyjo.com", "emoji": "🎯"},
  {"name": "ai-readiness-radar", "title": "AI 활용 준비도 진단", "keywords": "AI 리터러시, 업무 자동화, 디지털 전환", "target": "AI 시대에 대비하려는 직장인", "category": "일·커리어", "url": "https://ai-readiness-radar.pomyjo.com", "emoji": "🤖"},
  {"name": "attachment-style-radar", "title": "애착 유형 진단", "keywords": "관계 패턴, 애착 이론, 연애 심리", "target": "건강한 관계를 원하는 성인", "category": "성격·심리", "url": "https://attachment-style-radar.pomyjo.com", "emoji": "💞"},
  {"name": "burnout-prevention-radar", "title": "번아웃 예방 진단", "keywords": "번아웃 증후군, 스트레스 관리, 워라밸", "target": "번아웃 위험에 노출된 직장인", "category": "건강·습관", "url": "https://burnout-prevention-radar.pomyjo.com", "emoji": "🪫"},
  {"name": "burnout-recovery-radar", "title": "번아웃 회복 진단", "keywords": "번아웃 회복, 에너지 관리, 심리 회복", "target": "번아웃을 겪고 회복 중인 사람", "category": "건강·습관", "url": "https://burnout-recovery-radar.pomyjo.com", "emoji": "🪫"},
  {"name": "caffeine-dependency-radar", "title": "카페인 의존도 진단", "keywords": "카페인 섭취, 수면, 건강 습관", "target": "커피를 매일 마시는 현대인", "category": "건강·습관", "url": "https://caffeine-dependency-radar.pomyjo.com", "emoji": "☕"},
  {"name": "caffeine-half-life-clock", "title": "카페인 반감기 계산기", "keywords": "카페인 대사, 수면 최적화, 타이밍", "target": "카페인과 수면을 관리하려는 사람", "category": "건강·습관", "url": "https://caffeine-half-life-clock.pomyjo.com", "emoji": "☕"},
  {"name": "crypto-fomo-radar", "title": "크립토 FOMO 진단", "keywords": "가상자산 투자 심리, FOMO, 리스크", "target": "가상자산 투자자", "category": "기타", "url": "https://crypto-fomo-radar.pomyjo.com", "emoji": "😱"},
  {"name": "defensiveness-radar", "title": "방어성 진단", "keywords": "방어 기제, 피드백 수용, 성장 마인드셋", "target": "성장을 원하는 직장인", "category": "성격·심리", "url": "https://defensiveness-radar.pomyjo.com", "emoji": "🛡️"},
  {"name": "digital-detox-radar", "title": "디지털 디톡스 진단", "keywords": "스마트폰 중독, SNS 사용, 디지털 웰빙", "target": "스마트폰에 많은 시간을 쓰는 사람", "category": "건강·습관", "url": "https://digital-detox-radar.pomyjo.com", "emoji": "📵"},
  {"name": "empathy-fatigue-radar", "title": "공감 피로 진단", "keywords": "공감 피로, 돌봄 노동, 정서적 소진", "target": "돌봄·상담·헬스케어 종사자", "category": "성격·심리", "url": "https://empathy-fatigue-radar.pomyjo.com", "emoji": "💗"},
  {"name": "financial-anxiety-radar", "title": "금융 불안 진단", "keywords": "재정 스트레스, 불안 심리, 재무 관리", "target": "재정 걱정이 많은 직장인", "category": "건강·습관", "url": "https://financial-anxiety-radar.pomyjo.com", "emoji": "💸"},
  {"name": "fitness-mindset-radar", "title": "피트니스 마인드셋 진단", "keywords": "운동 동기, 습관 형성, 헬스 심리", "target": "운동을 시작하려는 사람", "category": "건강·습관", "url": "https://fitness-mindset-radar.pomyjo.com", "emoji": "💪"},
  {"name": "introvert-charm-radar", "title": "내향인 매력 진단", "keywords": "내향성 강점, 사회적 에너지, 자기 이해", "target": "내향적인 성격의 사람", "category": "성격·심리", "url": "https://introvert-charm-radar.pomyjo.com", "emoji": "🐢"},
  {"name": "mindfulness-zen-radar", "title": "마음챙김 수준 진단", "keywords": "명상, 마음챙김, 스트레스 완화", "target": "명상을 시작하려는 사람", "category": "건강·습관", "url": "https://mindfulness-zen-radar.pomyjo.com", "emoji": "🧘"},
  {"name": "networking-battery-radar", "title": "네트워킹 에너지 진단", "keywords": "대인 에너지, 네트워킹, 관계 관리", "target": "네트워킹이 필요한 직장인", "category": "건강·습관", "url": "https://networking-battery-radar.pomyjo.com", "emoji": "🤝"},
  {"name": "notion-obsessive-radar", "title": "노션 의존도 진단", "keywords": "생산성 도구, 디지털 워크플로우, 과잉 정리", "target": "생산성 도구를 쓰는 사람", "category": "건강·습관", "url": "https://notion-obsessive-radar.pomyjo.com", "emoji": "📓"},
  {"name": "perfectionism-radar", "title": "완벽주의 성향 진단", "keywords": "완벽주의, 자기 기준, 심리적 건강", "target": "완벽주의 성향의 직장인", "category": "기타", "url": "https://perfectionism-radar.pomyjo.com", "emoji": "💎"},
  {"name": "persona-mask-radar", "title": "페르소나 가면 진단", "keywords": "사회적 가면, 정체성, 진정성", "target": "자기 자신을 찾고 싶은 사람", "category": "성격·심리", "url": "https://persona-mask-radar.pomyjo.com", "emoji": "🎭"},
  {"name": "procrastination-radar", "title": "미루기 습관 진단", "keywords": "행동 지연, 실행력, 동기부여", "target": "일을 미루는 습관이 있는 사람", "category": "건강·습관", "url": "https://procrastination-radar.pomyjo.com", "emoji": "🐌"},
  {"name": "reward-spending-radar", "title": "보상 소비 진단", "keywords": "감정 소비, 소비 습관, 재정 건강", "target": "충동 구매를 하는 사람", "category": "건강·습관", "url": "https://reward-spending-radar.pomyjo.com", "emoji": "🎁"},
  {"name": "runway-calculator", "title": "스타트업 런웨이 계산기", "keywords": "자금 소진율, 스타트업 재무, 생존 기간", "target": "스타트업 창업자", "category": "건강·습관", "url": "https://runway-calculator.pomyjo.com", "emoji": "🛫"},
  {"name": "sleep-hygiene-radar", "title": "수면 위생 진단", "keywords": "수면 습관, 불면증, 수면의 질", "target": "수면의 질이 낮은 현대인", "category": "건강·습관", "url": "https://sleep-hygiene-radar.pomyjo.com", "emoji": "😴"},
  {"name": "subscription-fatigue-radar", "title": "구독 피로 진단", "keywords": "구독 서비스, 구독 경제, 지출 관리", "target": "구독 서비스를 많이 쓰는 사람", "category": "기타", "url": "https://subscription-fatigue-radar.pomyjo.com", "emoji": "🧩"},
  {"name": "argument-recovery-radar", "title": "논쟁 회복 진단", "keywords": "갈등 해소, 감정 회복, 관계 개선", "target": "다툼 후 회복이 어려운 사람", "category": "기타", "url": "https://argument-recovery-radar.pomyjo.com", "emoji": "🧩"},
  {"name": "assertion-style-radar", "title": "주장 스타일 진단", "keywords": "자기표현, 의사소통, 어설션", "target": "의견 표현이 어려운 사람", "category": "성격·심리", "url": "https://assertion-style-radar.pomyjo.com", "emoji": "💪"},
  {"name": "async-work-radar", "title": "비동기 업무 적합도 진단", "keywords": "원격 근무, 비동기 커뮤니케이션, 워크플로우", "target": "원격 근무자·프리랜서", "category": "일·커리어", "url": "https://async-work-radar.pomyjo.com", "emoji": "🔄"},
  {"name": "FIRE-readiness-radar", "title": "FIRE 준비도 진단", "keywords": "조기 은퇴, 재정 독립, 투자 전략", "target": "FIRE를 꿈꾸는 직장인", "category": "일·커리어", "url": "https://FIRE-readiness-radar.pomyjo.com", "emoji": "🏖️"},
  {"name": "digital-sovereignty-fit", "title": "디지털 주권 적합도 진단", "keywords": "데이터 자율성, 디지털 독립, 프라이버시", "target": "디지털 프라이버시를 중시하는 사람", "category": "일·커리어", "url": "https://digital-sovereignty-fit.pomyjo.com", "emoji": "🔐"},
  {"name": "side-hustle-fit", "title": "사이드허슬 적합도 진단", "keywords": "부업, N잡, 수익 창출", "target": "부업을 고민하는 직장인", "category": "일·커리어", "url": "https://side-hustle-fit.pomyjo.com", "emoji": "🚀"},
  {"name": "imposter-syndrome-radar", "title": "가면 증후군 진단", "keywords": "내적 사기꾼, 자기 효능감, 자신감", "target": "자신감이 부족한 직장인", "category": "성격·심리", "url": "https://imposter-syndrome-radar.pomyjo.com", "emoji": "🎭"},
  {"name": "leadership-archetype", "title": "리더십 아키타입 진단", "keywords": "리더십 유형, 조직 관리, 영향력", "target": "리더·매니저", "category": "성격·심리", "url": "https://leadership-archetype.pomyjo.com", "emoji": "👑"},
  {"name": "conflict-style-radar", "title": "갈등 스타일 진단", "keywords": "갈등 해결, 대인 관계, 협상", "target": "갈등을 겪는 직장인", "category": "성격·심리", "url": "https://conflict-style-radar.pomyjo.com", "emoji": "⚔️"},
  {"name": "decision-paralysis-radar", "title": "결정 마비 진단", "keywords": "의사결정, 선택 불안, 효율성", "target": "결정을 어려워하는 사람", "category": "건강·습관", "url": "https://decision-paralysis-radar.pomyjo.com", "emoji": "🤔"},
  {"name": "grit-focus-radar", "title": "그릿 지수 진단", "keywords": "열정, 인내, 장기 목표", "target": "장기 목표를 가진 사람", "category": "일·커리어", "url": "https://grit-focus-radar.pomyjo.com", "emoji": "🏔️"},
  {"name": "micro-achievement-journal", "title": "마이크로 성취 일지", "keywords": "작은 성취, 습관, 동기부여", "target": "성취감이 부족한 직장인", "category": "일·커리어", "url": "https://micro-achievement-journal.pomyjo.com", "emoji": "✅"},
  {"name": "micro-break-routine", "title": "마이크로 브레이크 가이드", "keywords": "짧은 휴식, 업무 효율, 회복", "target": "업무 중 휴식이 필요한 직장인", "category": "건강·습관", "url": "https://micro-break-routine.pomyjo.com", "emoji": "🧘"},
  {"name": "deep-work-battery", "title": "딥워크 배터리 진단", "keywords": "몰입, 집중력, 방해 요소", "target": "몰입이 어려운 지식 노동자", "category": "일·커리어", "url": "https://deep-work-battery.pomyjo.com", "emoji": "📚"},
  {"name": "code-review-roulette", "title": "코드리뷰 룰렛", "keywords": "코드 리뷰, 개발 문화, 협업", "target": "개발자·개발팀", "category": "일·커리어", "url": "https://code-review-roulette.pomyjo.com", "emoji": "🔍"},
  {"name": "prompt-efficiency-score", "title": "프롬프트 효율 진단", "keywords": "AI 프롬프트, LLM 활용, 프롬프트 엔지니어링", "target": "AI 도구를 쓰는 사람", "category": "일·커리어", "url": "https://prompt-efficiency-score.pomyjo.com", "emoji": "⌨️"},
  {"name": "meeting-cost-clock", "title": "회의 비용 계산기", "keywords": "회의 효율, 시간 비용, 업무 생산성", "target": "회의가 많은 직장인", "category": "일·커리어", "url": "https://meeting-cost-clock.pomyjo.com", "emoji": "⏱️"},
  {"name": "regret-spending-log", "title": "후회 지출 일지", "keywords": "소비 후회, 지출 관리, 재정 습관", "target": "후회하는 소비를 줄이고 싶은 사람", "category": "건강·습관", "url": "https://regret-spending-log.pomyjo.com", "emoji": "😔"},
  {"name": "subtle-sabotage-test", "title": "자기방해 패턴 진단", "keywords": "자기 방해, 습관, 성장", "target": "자기 방해 패턴이 있는 사람", "category": "성격·심리", "url": "https://subtle-sabotage-test.pomyjo.com", "emoji": "🕵️"},
  {"name": "async-readiness-index", "title": "비동기 전환 준비도 진단", "keywords": "조직 변화, 비동기 근무, 문화 전환", "target": "조직 전환을 준비하는 리더", "category": "일·커리어", "url": "https://async-readiness-index.pomyjo.com", "emoji": "🔄"},
  {"name": "hyper-automation-tower", "title": "하이퍼 오토메이션 진단", "keywords": "업무 자동화, AI 에이전트, 생산성", "target": "업무를 자동화하려는 직장인", "category": "건강·습관", "url": "https://hyper-automation-tower.pomyjo.com", "emoji": "🤖"},
  {"name": "mz-radar", "title": "MZ 트렌드 진단", "keywords": "MZ 세대, 트렌드, 자기 이해", "target": "MZ 세대 직장인", "category": "성격·심리", "url": "https://mz-radar.pomyjo.com", "emoji": "🕶️"},
  {"name": "genius-radar", "title": "지능 유형 진단", "keywords": "다중 지능, 재능 발견, 자기 개발", "target": "자신의 재능을 찾는 사람", "category": "성격·심리", "url": "https://genius-radar.pomyjo.com", "emoji": "🧠"},
  {"name": "fx-radar", "title": "FX 트레이딩 성향 진단", "keywords": "외환 거래, 투자 심리, 리스크", "target": "FX 트레이더", "category": "기타", "url": "https://fx-radar.pomyjo.com", "emoji": "💱"},
  {"name": "mood-weather", "title": "기분 날씨 진단", "keywords": "감정 일기, 기분 추적, 정서 관리", "target": "감정을 기록하는 사람", "category": "기타", "url": "https://mood-weather.pomyjo.com", "emoji": "🌦️"},
  {"name": "burnout-radar", "title": "번아웃 레이더", "keywords": "번아웃, 스트레스, 회복", "target": "번아웃을 겪는 직장인", "category": "기타", "url": "https://burnout-radar.pomyjo.com", "emoji": "🪫"},
  {"name": "money-radar", "title": "돈 습관 진단", "keywords": "재무 습관, 돈 관리, 소비 패턴", "target": "돈 관리를 시작하는 사람", "category": "성격·심리", "url": "https://money-radar.pomyjo.com", "emoji": "💰"},
  {"name": "side-hustle-radar", "title": "사이드허슬 레이더", "keywords": "부업, 수익, 시간 관리", "target": "부업을 원하는 직장인", "category": "일·커리어", "url": "https://side-hustle-radar.pomyjo.com", "emoji": "🚀"},
  {"name": "true-hourly-rate", "title": "진짜 시급 계산기", "keywords": "시급 계산, 시간 가치, 재무", "target": "시간의 가치를 계산하는 직장인", "category": "기타", "url": "https://true-hourly-rate.pomyjo.com", "emoji": "🧩"},
  {"name": "control-tower", "title": "사이트 운영 대시보드", "keywords": "모니터링, 운영, 통계", "target": "사이트 운영자", "category": "일·커리어", "url": "https://control-tower.pomyjo.com", "emoji": "🎛️"},
  {"name": "harness-report", "title": "하네스 리포트", "keywords": "성과 보고, 데이터, 인사이트", "target": "경영진·매니저", "category": "기타", "url": "https://harness-report.pomyjo.com", "emoji": "🔧"},
  {"name": "jeongbu", "title": "정부지원 가이드", "keywords": "정부 지원금, 혜택, 신청", "target": "정부 지원을 찾는 사람", "category": "기타", "url": "https://jeongbu.pomyjo.com", "emoji": "🧩"},
  {"name": "jikjang", "title": "직장인 가이드", "keywords": "직장 생활, 커리어, 워라밸", "target": "직장인", "category": "일·커리어", "url": "https://jikjang.pomyjo.com", "emoji": "🏢"},
  {"name": "serverguchuk1024", "title": "서버 구축 가이드", "keywords": "서버, 인프라, 클라우드", "target": "서버를 구축하는 개발자", "category": "일·커리어", "url": "https://serverguchuk1024.pomyjo.com", "emoji": "🖥️"},
  {"name": "ilban-leadership-site", "title": "일반 리더십 가이드", "keywords": "리더십, 관리, 조직", "target": "신임 리더", "category": "기타", "url": "https://ilban-leadership-site.pomyjo.com", "emoji": "👑"},
  {"name": "sinang-inside", "title": "신앙 인사이드", "keywords": "신앙, 묵상, 영성", "target": "신앙 생활을 하는 사람", "category": "기타", "url": "https://sinang-inside.pomyjo.com", "emoji": "💫"},
  {"name": "sibiljo", "title": "십일조 분석 도구", "keywords": "십일조, 재무 분석, 신앙", "target": "교회 재무 담당자", "category": "일·커리어", "url": "https://sibiljo.pomyjo.com", "emoji": "📝"},
  {"name": "regulation-hub", "title": "규정 허브", "keywords": "규정, 정책, 법규", "target": "규정을 찾는 직장인", "category": "기타", "url": "https://regulation-hub.pomyjo.com", "emoji": "🧩"},
  {"name": "make-it-mine-35", "title": "메이크 잇 마인 35", "keywords": "자기 개발, 습관, 성장", "target": "자기 개발을 원하는 사람", "category": "기타", "url": "https://make-it-mine-35.pomyjo.com", "emoji": "🧩"},
  {"name": "Gajeong", "title": "가정월드", "keywords": "가정, 관계, 생활", "target": "가족", "category": "기타", "url": "https://Gajeong.pomyjo.com", "emoji": "🧩"},
  {"name": "juganbogo3", "title": "주간 보고 도구", "keywords": "주간 보고, 업무 관리, 생산성", "target": "주간 보고를 쓰는 직장인", "category": "건강·습관", "url": "https://juganbogo3.pomyjo.com", "emoji": "📊"},
  {"name": "juganbogo4", "title": "주간 보고 프로", "keywords": "주간 보고, 회고, 생산성", "target": "회고를 하는 직장인", "category": "건강·습관", "url": "https://juganbogo4.pomyjo.com", "emoji": "📊"},
  {"name": "SOMOPUMGWANRI", "title": "소모품 관리", "keywords": "자산 관리, 재고, 사무실 운영", "target": "사무 관리자", "category": "기타", "url": "https://SOMOPUMGWANRI.pomyjo.com", "emoji": "🧩"},
  {"name": "MIRRIOR-APP", "title": "미러 앱", "keywords": "셀카, 거울, 이미지", "target": "이미지 편집 사용자", "category": "기타", "url": "https://MIRRIOR-APP.pomyjo.com", "emoji": "🧩"},
  {"name": "dowajoyo", "title": "도와줘요", "keywords": "도움 요청, 커뮤니티, 질문", "target": "도움이 필요한 사람", "category": "일·커리어", "url": "https://dowajoyo.pomyjo.com", "emoji": "🤝"},
  {"name": "trend-dashboard", "title": "트렌드 대시보드", "keywords": "트렌드, 데이터, 인사이트", "target": "트렌드를 보는 마케터", "category": "기타", "url": "https://trend-dashboard.pomyjo.com", "emoji": "📈"},
  {"name": "FocusFlow1024", "title": "포커스 플로우", "keywords": "집중, 플로우, 생산성", "target": "집중력이 필요한 직장인", "category": "기타", "url": "https://FocusFlow1024.pomyjo.com", "emoji": "🧩"},
  {"name": "aikiugihimdulda", "title": "아이큐어 기힘들다", "keywords": "건강, 피로, 회복", "target": "피로한 현대인", "category": "기타", "url": "https://aikiugihimdulda.pomyjo.com", "emoji": "🧩"},
  {"name": "MindPrism1024", "title": "마인드 프리즘", "keywords": "심리, 감정, 자기 이해", "target": "심리를 탐구하는 사람", "category": "기타", "url": "https://MindPrism1024.pomyjo.com", "emoji": "🧩"},
  {"name": "chotan", "title": "초단 관리", "keywords": "시간 관리, 초단위, 생산성", "target": "시간 관리를 원하는 사람", "category": "기타", "url": "https://chotan.pomyjo.com", "emoji": "🌐"},
  {"name": "ilban-leadership", "title": "일반 리더십", "keywords": "리더십, 자기 개발, 영향력", "target": "리더십을 기르는 사람", "category": "기타", "url": "https://ilban-leadership.pomyjo.com", "emoji": "👑"},
  {"name": "tongHAP", "title": "통합 관리", "keywords": "통합 대시보드, 관리, 운영", "target": "운영 관리자", "category": "기타", "url": "https://tongHAP.pomyjo.com", "emoji": "🧩"},
];