// 76개 진단 학술 근거 매핑
export const SCIENCE: Record<string, { theory: string; scholars: string; ref: string }> = {
  "adhd-focus-radar": { theory: "주의력 결핍 과잉행동장애 진단기준", scholars: "DSM-5 (APA, 2013)", ref: "Brown Attention Deficit Disorder Scales" },
  "ai-readiness-radar": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "attachment-style-radar": { theory: "애착 이론 (Attachment Theory)", scholars: "Bowlby (1969), Ainsworth (1978)", ref: "Strange Situation 절차 기반" },
  "burnout-prevention-radar": { theory: "직무소진 모델", scholars: "Maslach & Jackson (1981)", ref: "Maslach Burnout Inventory (MBI)" },
  "burnout-recovery-radar": { theory: "직무소진 모델", scholars: "Maslach & Jackson (1981)", ref: "Maslach Burnout Inventory (MBI)" },
  "caffeine-dependency-radar": { theory: "카페인 사용장애와 수면의학", scholars: "DSM-5 카페인 관련 장애", ref: "카페인 대사 반감기 연구" },
  "caffeine-half-life-clock": { theory: "카페인 사용장애와 수면의학", scholars: "DSM-5 카페인 관련 장애", ref: "카페인 대사 반감기 연구" },
  "crypto-fomo-radar": { theory: "FOMO와 사회적 연결 욕구", scholars: "Przybylski et al. (2013)", ref: "FOMO 척도 (Przybylski)" },
  "defensiveness-radar": { theory: "방어기제 이론", scholars: "Anna Freud (1936), Cramer (2006)", ref: "Defense Mechanism Rating Scales" },
  "digital-detox-radar": { theory: "디지털 웰빙과 스마트폰 사용", scholars: "Nomophobia 연구, Twenge (2017)", ref: "Nomophobia Questionnaire (NMP-Q)" },
  "empathy-fatigue-radar": { theory: "공감피로 (Compassion Fatigue)", scholars: "Figley (1995)", ref: "Professional Quality of Life Scale (ProQOL)" },
  "financial-anxiety-radar": { theory: "재무스트레스와 심리적 웰빙", scholars: "Financial Stress Index, Kahneman (2011)", ref: "행동경제학, 전망이론" },
  "fitness-mindset-radar": { theory: "습관 형성 이론", scholars: "Lally et al. (2010)", ref: "습관 루프 (cue-routine-reward)" },
  "introvert-charm-radar": { theory: "내향성-외향성 차원", scholars: "Jung (1921), Eysenck (1967)", ref: "Big Five 내향성 하위척도" },
  "mindfulness-zen-radar": { theory: "마음챙김 (Mindfulness)", scholars: "Kabat-Zinn (1990)", ref: "MBSR, Five Facet Mindfulness Questionnaire" },
  "networking-battery-radar": { theory: "사회적 에너지와 대인관계", scholars: "Jung (1921), Little (2011)", ref: "자유성격이론 (Free Trait Theory)" },
  "notion-obsessive-radar": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "perfectionism-radar": { theory: "다차원 완벽주의 이론", scholars: "Hewitt & Flett (1991)", ref: "Multidimensional Perfectionism Scale (MPS)" },
  "persona-mask-radar": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "procrastination-radar": { theory: "시간동기이론 (Temporal Motivation Theory)", scholars: "Steel & König (2006)", ref: "일반미루기척도 (GPS)" },
  "reward-spending-radar": { theory: "충동구매/감정소비 심리", scholars: "Faber & O'Guinn (1992)", ref: "Compulsive Buying Scale (CBS)" },
  "runway-calculator": { theory: "진로 발달 이론", scholars: "Super (1980), Holland (1959)", ref: "진로 성숙도 모델" },
  "sleep-hygiene-radar": { theory: "수면위생 및 수면의학", scholars: "AASM, Espie (2002)", ref: "Pittsburgh Sleep Quality Index (PSQI)" },
  "subscription-fatigue-radar": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "argument-recovery-radar": { theory: "대인관계 심리학", scholars: "Gottman (1999), Leary (1957)", ref: "관계 만족도 연구" },
  "assertion-style-radar": { theory: "주장성 훈련 (Assertiveness Training)", scholars: "Wolpe (1958), Alberti & Emmons (1974)", ref: "Rathus Assertiveness Schedule" },
  "async-work-radar": { theory: "원격/비동기 업무 연구", scholars: "Rico & Cohen (2020)", ref: "분산팀 커뮤니케이션 연구" },
  "FIRE-readiness-radar": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "digital-sovereignty-fit": { theory: "디지털 웰빙과 스마트폰 사용", scholars: "Nomophobia 연구, Twenge (2017)", ref: "Nomophobia Questionnaire (NMP-Q)" },
  "side-hustle-fit": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "imposter-syndrome-radar": { theory: "가면증후군 (Impostor Phenomenon)", scholars: "Clance & Imes (1978)", ref: "Clance Impostor Phenomenon Scale (CIPS)" },
  "leadership-archetype": { theory: "진로 발달 이론", scholars: "Super (1980), Holland (1959)", ref: "진로 성숙도 모델" },
  "conflict-style-radar": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "decision-paralysis-radar": { theory: "선택의 역설", scholars: "Schwartz (2004)", ref: "Maximizer-Satisficer 척도" },
  "grit-focus-radar": { theory: "그릿 (Grit) 이론", scholars: "Duckworth et al. (2007)", ref: "Grit Scale (Duckworth)" },
  "micro-achievement-journal": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "micro-break-routine": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "deep-work-battery": { theory: "진로 발달 이론", scholars: "Super (1980), Holland (1959)", ref: "진로 성숙도 모델" },
  "code-review-roulette": { theory: "소프트웨어 개발 심리학", scholars: "Weinberg (1971), Dunning & Kruger (1999)", ref: "인지편향과 코드리뷰 연구" },
  "prompt-efficiency-score": { theory: "인간-AI 상호작용", scholars: "OpenAI 프롬프트 공학, Amershi et al. (2019)", ref: "HCI-AI 연구" },
  "meeting-cost-clock": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "regret-spending-log": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "subtle-sabotage-test": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "async-readiness-index": { theory: "원격/비동기 업무 연구", scholars: "Rico & Cohen (2020)", ref: "분산팀 커뮤니케이션 연구" },
  "hyper-automation-tower": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "mz-radar": { theory: "성격 5요인 (Big Five) + 직업흥미", scholars: "Costa & McCrae (1992), Holland (1959)", ref: "NEO-PI-R, Holland RIASEC" },
  "genius-radar": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "fx-radar": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "mood-weather": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "burnout-radar": { theory: "직무소진 모델", scholars: "Maslach & Jackson (1981)", ref: "Maslach Burnout Inventory (MBI)" },
  "money-radar": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "side-hustle-radar": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "true-hourly-rate": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "control-tower": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "harness-report": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "jeongbu": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "jikjang": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "serverguchuk1024": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "ilban-leadership-site": { theory: "진로 발달 이론", scholars: "Super (1980), Holland (1959)", ref: "진로 성숙도 모델" },
  "sinang-inside": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "sibiljo": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "regulation-hub": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "make-it-mine-35": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "Gajeong": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "juganbogo3": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "juganbogo4": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "SOMOPUMGWANRI": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "MIRRIOR-APP": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "dowajoyo": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "trend-dashboard": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "FocusFlow1024": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "aikiugihimdulda": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "MindPrism1024": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "chotan": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
  "ilban-leadership": { theory: "진로 발달 이론", scholars: "Super (1980), Holland (1959)", ref: "진로 성숙도 모델" },
  "tongHAP": { theory: "성격 심리학 일반", scholars: "Allport (1937), Big Five", ref: "성격 5요인 모델" },
};